package com.akafuri25.hikaku.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMPARE".
 */
public class Compare {

    private String productId;
    private String name;
    private Double price;
    private String url;
    private String source;
    private String images;
    private String description;
    private String location;

    public Compare() {
    }

    public Compare(String productId) {
        this.productId = productId;
    }

    public Compare(String productId, String name, Double price, String url, String source, String images, String description, String location) {
        this.productId = productId;
        this.name = name;
        this.price = price;
        this.url = url;
        this.source = source;
        this.images = images;
        this.description = description;
        this.location = location;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getImages() {
        return images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

}
