package com.akafuri25.hikaku.data;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.akafuri25.hikaku.data.Product;
import com.akafuri25.hikaku.data.Wishlist;
import com.akafuri25.hikaku.data.Compare;

import com.akafuri25.hikaku.data.ProductDao;
import com.akafuri25.hikaku.data.WishlistDao;
import com.akafuri25.hikaku.data.CompareDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig productDaoConfig;
    private final DaoConfig wishlistDaoConfig;
    private final DaoConfig compareDaoConfig;

    private final ProductDao productDao;
    private final WishlistDao wishlistDao;
    private final CompareDao compareDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        wishlistDaoConfig = daoConfigMap.get(WishlistDao.class).clone();
        wishlistDaoConfig.initIdentityScope(type);

        compareDaoConfig = daoConfigMap.get(CompareDao.class).clone();
        compareDaoConfig.initIdentityScope(type);

        productDao = new ProductDao(productDaoConfig, this);
        wishlistDao = new WishlistDao(wishlistDaoConfig, this);
        compareDao = new CompareDao(compareDaoConfig, this);

        registerDao(Product.class, productDao);
        registerDao(Wishlist.class, wishlistDao);
        registerDao(Compare.class, compareDao);
    }
    
    public void clear() {
        productDaoConfig.getIdentityScope().clear();
        wishlistDaoConfig.getIdentityScope().clear();
        compareDaoConfig.getIdentityScope().clear();
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public WishlistDao getWishlistDao() {
        return wishlistDao;
    }

    public CompareDao getCompareDao() {
        return compareDao;
    }

}
