package com.akafuri25.hikaku.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WISHLIST".
 */
public class Wishlist {

    private String productId;
    private String name;
    private Double price;
    private String url;
    private String source;
    private String image;
    private String location;

    public Wishlist() {
    }

    public Wishlist(String productId) {
        this.productId = productId;
    }

    public Wishlist(String productId, String name, Double price, String url, String source, String image, String location) {
        this.productId = productId;
        this.name = name;
        this.price = price;
        this.url = url;
        this.source = source;
        this.image = image;
        this.location = location;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

}
